### PR TITLE
Fix #223 by skipping the setting of object_id if it is empty

### LINKED ISSUE #223: Error: This vat only supports a bootstrap interface, not the old Cap'n-Proto-0.4-style named exports
I'm trying to use capnp to connect an Ocaml process to a Python process. I have successfully followed the 'echo'-tutorial of `capnp-rpc`, getting an Ocaml client to talk to an Ocaml server. I created a similar setup in Python (having two python processes talk to each other). Now I wish to run the echo-server in a Python process and use an Ocaml client to connect to it. However, I am met with the following error:
```
atal error: exception (Failure
  "Error calling field(2) -> Failed: This vat only supports a bootstrap interface, not the old Cap'n-Proto-0.4-style named exports.(Echo.ping): Failed: This vat only supports a bootstrap interface, not the old Cap'n-Proto-0.4-style named exports.")
```
This error seems to originate from the C++ code that Python binds to:
https://github.com/capnproto/capnproto/blob/3f01eac812af3ca863d55981423fb90c08be0809/c%2B%2B/src/capnp/rpc.c%2B%2B#L2579-L2580

Am I doing something wrong while calling for the service, or is the implementation still using these 0.4-style named exports? Below is the code to reproduce:
```
@0xafda4797418def92;

interface Echo {
  ping @0 (msg :Text) -> (reply :Text);
}
```
```ocaml
open Lwt.Infix
open Capnp_rpc_lwt

let () =
  Logs.set_level (Some Logs.Warning);
  Logs.set_reporter (Logs_fmt.reporter ())

let run_client service =
  Echo_client.ping service "foo" >>= fun reply ->
  Fmt.pr "Got reply %S@." reply;
  Lwt.return_unit

let () =
  Lwt_main.run begin
    let client_vat = Capnp_rpc_unix.client_only_vat () in
    let sr = Capnp_rpc_unix.Vat.import_exn client_vat @@ Uri.of_string "capnp://insecure@localhost:5001" in
    Sturdy_ref.with_cap_exn sr run_client
  end
```
```python
#!/usr/bin/env python3

import argparse
import capnp
import time

import echo_api_capnp

class EchoImpl(echo_api_capnp.Echo.Server):

    def ping(self, msg, _context):
        print(msg)
        print(_context)
        return "boe"


def parse_args():
    parser = argparse.ArgumentParser(usage='''Runs the server bound to the\
given address/port ADDRESS may be '*' to bind to all local addresses.\
:PORT may be omitted to choose a port automatically. ''')

    parser.add_argument("address", help="ADDRESS[:PORT]")

    return parser.parse_args()


def main():
    address = parse_args().address

    server = capnp.TwoPartyServer(address, bootstrap=EchoImpl())
    while True:
        server.poll_once()
        time.sleep(0.001)


if __name__ == '__main__':
    main()
```

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**

### CODE REVIEW

**Comment by talex5** [comment]
Thanks!

**Comment by LasseBlaauwbroek** [comment]
Thanks for your help in resolving this. Do you have an estimate of when you might make a new release? I'm looking to use capnp-rpc in production, so it would be convenient if I could use a released package.

**Comment by talex5** [comment]
Probably in a few weeks. It hasn't been tested much with the C++ version, so you might find other things!

What I normally do with projects using the latest version `git submodule add https://github.com/mirage/capnp-rpc.git` in the project directory. Then dune will automatically pick up the capnp-rpc subdirectory and build against that version.

**Comment by LasseBlaauwbroek** [comment]
Great thanks

**Pull request merged**
