### PR TITLE
adjust to mirage-stack / mirage-protocols changes - mirage/test

### PR DESCRIPTION
**Pull request by nickbetteridge**
Compiling now after mirage-stack / mirage-protocols changes

### CODE REVIEW

**Comment by nickbetteridge** [comment]
Uhm - I can see that travis is failing on a dependency - not too sure which docker ocaml/opam image to use?

**Comment by nickbetteridge** [comment]
Still failing - it's looking for ```libssl-dev_1.1.0f-3+deb9u1_amd64.deb``` in ```http://security.debian.org/pool/updates/main/o/openssl``` where there is only an updated version of ```libssl-dev_1.1.0j-1~deb9u1_amd64.deb```. I'm no Docker expert - could you possibly recommend a suitable docker definition from ```https://github.com/ocaml-attic/opam-dockerfiles```?

**Comment by talex5** [comment]
Oh, right, it's using the opam 1 image, which hasn't been updated for a year, so it's using an old version of Debian. Switching to opam 2 might help:

```
FROM ocaml/opam2@sha256:507d4e2786904e3d19ca6db6f6a482af131c9fe6b2597ba62add762305d5c0fb
#FROM ocaml/opam2:debian-9-ocaml-4.07
```

Alternatively, running `apt-get update` first might solve the problem too.

Either way, you'll need to update the `git reset` line to a recent version of opam repository that has the new version of Mirage you want to use.

**Comment by talex5** [comment]
(you also need to remove the `cd opam-repository &&` bit to use opam 2)

**Comment by nickbetteridge** [comment]
Thanks for the help - found another niggle, fixed - should have learnt docker/travis properly a long time ago!

**Comment by talex5** [comment]
Thanks!

**Pull request merged**
