### PR TITLE
Update to new x509 API

### PR DESCRIPTION
**Pull request by talex5**
See https://github.com/ocaml/opam-repository/pull/14592#issuecomment-515625513

/cc @hannesm

### CODE REVIEW

**Comment by hannesm** [comment]
that looks good! :)

**Comment by hannesm** [comment]
(the only nit being: you should include the dependency `"x509" {>= "0.7.0"}` in the opam file

**Comment by talex5** [comment]
> (the only nit being: you should include the dependency "x509" {>= "0.7.0"} in the opam file

It's already there (in `capnp-rpc-lwt.opam`).

**Comment by hannesm** [comment]
oops, sorry -- shouldn't read diffs before finishing coffee

**Pull request merged**
