### PR TITLE
Better way to get the client certificate from a TLS connection

### PR DESCRIPTION
**Pull request by talex5**
Suggested by @hannesm in https://github.com/mirage/capnp-rpc/issues/126#issuecomment-331843320

### CODE REVIEW

**Comment by hannesm** [comment]
this looks much nicer (less `ref` is always good!), but I've two more questions:
 - you require a client certificate! -- I'd expect a failure if you _have to_ connect back, and you didn't receive a client cert in the initial connection (there are valid rpc services without connections back, or?)
 - you preserve only the digest of the client certificate, not the public key of it -- this means the public key is not needed (and retransmitted anyways if you connect as client to the server, and only afterwards needed)?

**Comment by talex5** [comment]
If you didn't receive a cert in the initial connection then you don't know when you're trying to connect back to that client. It would be possible to allow TLS clients without certs, but it complicates the logic, so passing a cert in all cases seemed easier.

Yes, we only store the digest of the public key, not the key itself. But doesn't TLS need the client's public key to check that the client controls the corresponding private key somehow?

**Comment by hannesm** [comment]
"But doesn't TLS need the client's public key to check that the client controls the corresponding private key somehow?" -- this is done during the TLS handshake itself: after the client certificate is sent over the wire, a [CertificateVerify](https://tools.ietf.org/html/rfc5246#section-7.4.8) message has to be sent.  In the OCaml-TLS API, you'll only ever see TLS connections where the CertificateVerify was sent by the client and validated correctly (i.e. the client presented a proof that it has access to the private key of the certificate).

**Comment by talex5** [comment]
OK, good. That's what I thought. What do you mean by "this means the public key is not needed"? The client has to send it, and TLS keeps a copy in the epoch data.

**Comment by hannesm** [comment]
I was curious whether cap'n proto rpc needs this public key for any cryptographic operations... but it sounds that it uses only their fingerprint for authentication purposes (which is fine)

**Comment by talex5** [comment]
This way of using TLS for capnp is just something I wrote, although it would be nice to get it made official. The other implementations don't seem to support security at all, although there is this cluster system (which appears to be doing its own crypto):

https://github.com/sandstorm-io/blackrock/blob/master/src/blackrock/cluster-rpc.capnp#L249

I don't know what its status is.

**Pull request merged**
