### PR TITLE
update to mirage-crypto-rng 0.11 and dns 7.0.0 API changes

### PR DESCRIPTION
**Pull request by hannesm**
requires https://github.com/ocaml/opam-repository/pull/23332 to be merged

### CODE REVIEW

**Comment by hannesm** [comment]
this is fine to merge now (dns 7.0.0 has been integrated into opam-repository). once landed in opam-repository, this will unblock https://github.com/ocurrent/ocurrent/pull/408

**Review by talex5 — APPROVED** [review]
The other CI failures are unrelated (see #262).

**Comment by hannesm** [comment]
Thanks for merging this. Would it be possible to have a release of capnp-rpc to allow dependent packages to upgrade to the new package layout of mirage-crypto-rng & dns & tls? Thanks a lot :)

**Comment by tmcgilchrist** [comment]
Working on a release for this.

**Pull request merged**
