### PR TITLE
adapt to x509 0.8.x API changes

### PR DESCRIPTION
**Pull request by hannesm**
once https://github.com/ocaml/opam-repository/pull/15034 is merged

### CODE REVIEW

**Comment by hannesm** [comment]
x509 0.8.1 is merged into opam now, I restarted the travis job (but couldn't find a restart button for ocaml-ci)

**Comment by talex5** [comment]
At the moment, ocaml-ci builds against a fixed Docker base image, which is updated once a week (so it should fix itself in a few days). Tracked at https://github.com/ocaml-ci/ocaml-ci/issues/26.

**Comment by hannesm** [comment]
@talex5 ic. I don't understand why the travis job here suffers from the same issue (i.e. cannot find x509 0.8.1).

**Comment by talex5** [comment]
> I don't understand why the travis job here suffers from the same issue (i.e. cannot find x509 0.8.1).

The Travis job just builds the Dockerfile, which needs to be updated with a recent-enough Git commit in opam-repository:

https://github.com/mirage/capnp-rpc/blob/master/Dockerfile#L3

**Comment by talex5** [comment]
I've made the change in #176.

**Pull request closed without merging**
