### PR TITLE
Update capnp-rpc-lwt.opam

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Testing the lower-bounds check for ocaml-ci

### CODE REVIEW

**Review by talex5 — APPROVED** [review]
Looks good to me. Why is it a draft?

Would be interesting to know why the Windows build is failing, but looks unrelated to this PR:
```
  the following programs are not installed properly:
   curl
  I can't proceed :(
```

**Comment by tmcgilchrist** [comment]
@talex5 issue with setup-ocaml on Windows https://github.com/ocaml/setup-ocaml/issues/645.

**Comment by tmcgilchrist** [comment]
This has a bug with the chosen lower bounds, the tests timeout. It is not clear whether it is caused by alcotest or dune. I am still debugging it by choosing newer versions of dependencies until it passes.

**Comment by talex5** [comment]
This seems bad:
```
utop # #require "stdint";;
utop # let max_val = Stdint.Uint32.to_int (Stdint.Uint32.max_int);;
val max_val : int = -1
```
It seems to have been fixed by https://github.com/andrenth/ocaml-stdint/commit/5e750d75221b8ad7d28b6b5b0bfb50a7e02f83c6 ("Migrate from jbuilder to dune"), which seems odd. Debugging it would require messing around with jbuilder, so probably capnproto just needs a lower-bound on stdint.

**Pull request closed without merging**
